# Mouse Control
set -g mouse on

# Split pane shortcuts
bind | split-window -h
bind - split-window -v

# Move through panes with Alt+Arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
